[build]
  command = "npm run build"
  publish = ".output/public"
  node_version = "22.12.0"

[build.environment]
  NODE_VERSION = "22.12.0"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200